services:
  plex-clear-watchlist:
    image: ghcr.io/blixten85/plex-clear-watchlist:latest
    container_name: plex-clear-watchlist
    pull_policy: always
    restart: "no"
    security_opt:
      - no-new-privileges:true
    environment:
      PLEX_TOKEN: ${PLEX_TOKEN}
